# hugo module configuration

# uncomment line below for temporary local development of module
# replacements: "github.com/mrmxf/fohuw -> ../../fohuw"
hugoVersion:
  extended: true
  min: v0.133.0
imports:
  - path: github.com/mrmxf/fohuw
    disable: false